# Generated by Django 4.1.1 on 2022-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0003_alter_blog_text_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
