# Generated by Django 4.1.1 on 2022-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0004_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
