# Generated by Django 4.1.1 on 2022-11-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0005_blog_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='upload_date',
        ),
    ]
