# Generated by Django 4.1.1 on 2022-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0007_remove_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.CharField(default='topic', max_length=255),
            preserve_default=False,
        ),
    ]
