# Generated by Django 4.1.1 on 2022-11-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0008_blog_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topics',
        ),
    ]
