# Generated by Django 4.1.1 on 2022-11-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0010_alter_blog_text_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
