# Generated by Django 4.1.1 on 2022-11-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0011_remove_blog_title_remove_contact_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
