# Generated by Django 4.1.1 on 2023-01-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0013_topic_alter_blog_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated',
        ),
    ]
