# Generated by Django 4.1.1 on 2023-01-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0016_alter_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
