# Generated by Django 4.1.1 on 2023-01-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JamesPortfolio_app', '0017_remove_contact_description_remove_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
    ]
